### ISSUE TITLE
About throttle on this project

### ISSUE THREAD

**Issue by codenoobforreal** [weibenfalk/react-hooks-tetris#1]
i had finished this stuff with your lesson (https://www.youtube.com/watch?v=ZGOaCxX8HIU) :+1::+1::+1:

Considering about gaming itself
when i keep pressing :arrow_down: , the game just stop a while util i release ⬇️ , then it comes to the very last stage on the screen.
So i want to add something like throttle to onkeydown event.

I began to google :world_map: "how to use throttle in react hooks"
like
https://codesandbox.io/s/18yyn08y7
https://twitter.com/dan_abramov/status/1060729512227467264
https://github.com/streamich/react-use/issues/372
https://stackoverflow.com/questions/54666401/how-to-use-throttle-or-debounce-with-react-hook/54666498

I tried these solutions but it didn't work  :thinking::pensive::dizzy_face:

Can you implement throttle on keyborad event ⬇️ ⬅️ ➡️ ⬆️  ?

By the way
before hitting start button,the interval is still working and the game just re-render every 1s.
`
  useInterval(() => {
    if (gameStart && !gameOver) {
      drop();
    }
  }, dropTime);
`

**Comment by weibenfalk** [comment]
Hey. Glad you like the course. I would love to help but I have a LOT to do right now and also a family to take care of. The controls aren't sophisticated at all in this app unfortunately. That was intentional as I didn't want to complicate things for the people taking the course. I just use the built in key repeat when the key is pressed now. 

So ... would love to help but my time is limited. Would love to know if you find a good solution to this though. 

The interval shouldn't be active if the dropTime isn't set. This is a custom hook built by Dan Abramov and it should reset itself if you set the dropTime to 0.

**Comment by codenoobforreal** [comment]
Take care !
Anyway thank you so much :+1:
